### ISSUE TITLE
Microsoft.SymbolStore

### ISSUE THREAD

**Issue by DJm00n** [nefarius/WinDbgSymbolsCachingProxy#1]
May be used in your project:
https://github.com/dotnet/symstore

**Comment by nefarius** [comment]
Very nice, will see if I can integrate more in the future, thanks!

**Comment by nefarius** [comment]
Another one: https://github.com/dotnet/symreader

**Comment by nefarius** [comment]
> May be used in your project: https://github.com/dotnet/symstore

I integrated it into the custom upload endpoint, this is really great, can compute the "keys" on Linux without any need for Windows libraries 🥳
