### ISSUE TITLE
[Visual Studio] Application not hitting cache

### ISSUE THREAD

**Issue by R4to0** [nefarius/WinDbgSymbolsCachingProxy#82]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When using with Visual Studio (2022 in my case), the proxy is not hitting cached files from mongo database, instead it is re-downloading the same objects again from upstream Microsoft servers. Noticed mongodb database increasing when requesting the same objects multiple times.

### Steps to reproduce

- have a local running instance of WinDbgSymbolsCachingProxy;
- have setup `http://127.0.0.1:5000/download/symbols` as your only symbol server in VS (pic 1);
- open a crashdump, start debugging and wait fetching all symbols;
- clear your local SymbolCache folder VS uses to store symbol files temporarily;
- repeat step 3

**Actual result:** proxy is bypassing cached objects and is directly fetching again from upstream MS servers, storing again in cache.
**Expected result:** proxy should read cached data from database and serve them.

### Screenshots

Visual Studio symbol server setting
![image](https://github.com/nefarius/WinDbgSymbolsCachingProxy/assets/3608184/72dd8346-f8c8-48b0-914b-101e7faac235)

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 11 Pro 22H2 build 22621.2715
**Software/driver version(s):** 7043996d1b897be543264261faa0b2f347b3d8aa

### Any other helpful information

Application logs attached.
[server-20231202.log](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537455/server-20231202.log)
[access-20231202.0001.txt](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537459/access-20231202.0001.txt)

**Comment by nefarius** [comment]
I think I know why; when querying the database, all strings are converted to lower-case. However, if the request was upper or mixed case, upon inserting a new entry, the original casing is used and since the comparison in the query is canse-sensitive, we never hit the cached symbol.

**Comment by R4to0** [comment]
Can confirm the issue went away with your latest commit. All the symbols were fetched from cache this time.
Got some unhandled exceptions when it returned 404 for non existent files but these are unrelated to this issue

High quality service right there! :)

Logs attached.

[server-20231202.log](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537525/server-20231202.log)
[access-20231202.0002.txt](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537526/access-20231202.0002.txt)

**Comment by nefarius** [comment]
Thanks for the logs, I will fix that exception as well, happens when a file is requested where only the meta-data exists but no binary blob.

**Comment by R4to0** [comment]
Here's another set of log files with commit e918dc65e0fcc3f7697b5c7bf359f3cd214597f7. There's some exceptions still, its backtrace/callstack is smaller compared to before.

```
System.InvalidOperationException: Data for this file hasn't been uploaded successfully (yet)!
   at MongoDB.Entities.DataStreamer.DownloadAsync(Stream stream, Int32 batchSize, CancellationToken cancellation, IClientSessionHandle session)
   at WinDbgSymbolsCachingProxy.Endpoints.SymbolsEndpoint.HandleAsync(SymbolsRequest req, CancellationToken ct) in D:\Repositories\WinDbgSymbolsCachingProxy\src\Endpoints\SymbolsEndpoint.cs:line 66
```

[server-20231202-4.log](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537607/server-20231202-4.log)
[access-20231202.0004.txt](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537608/access-20231202.0004.txt)

**Comment by nefarius** [comment]
Fix pushed.

**Comment by R4to0** [comment]
All clear now, no exceptions visible in the logs or application window.

Logs attached just in case.

[server-20231202-5.log](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537685/server-20231202-5.log)
[access-20231202.0005.txt](https://github.com/nefarius/WinDbgSymbolsCachingProxy/files/13537686/access-20231202.0005.txt)
